### ISSUE TITLE
The icons aren't right.

### ISSUE THREAD

**Issue by aasutossh** [betaboon/nerd-fonts-patcher#1]
Patched https://github.com/agarick/agave/ using the patcher. The icons look like following, 
![image](https://user-images.githubusercontent.com/18498932/88018268-185bb000-cb47-11ea-8e73-11c8e57cf182.png)
![image](https://user-images.githubusercontent.com/18498932/88018287-26113580-cb47-11ea-9256-eae3d187c829.png)

I used `fontforge -script font-patcher -w -c ../Agave-Regular.ttf`. I am using alacritty terminal with wsl2 windows 10.
It doesn't look right how to fix it?

**Comment by betaboon** [comment]
@aasutossh please address this issue upstream as this repository is just a mirror of the font-patcher files of https://github.com/ryanoasis/nerd-fonts
